import {
  adventurer,
  adventurerNeutral,
  avataaars,
  avataaarsNeutral,
  bigEars,
  bigEarsNeutral,
  bigSmile,
  bottts,
  botttsNeutral,
  croodles,
  croodlesNeutral,
  funEmoji,
  icons,
  identicon,
  lorelei,
  loreleiNeutral,
  micah,
  miniavs,
  notionists,
  notionistsNeutral,
  openPeeps,
  personas,
  pixelArt,
  pixelArtNeutral,
  rings,
  shapes,
  thumbs,
} from "@dicebear/collection";

export const STYLE_URL_MAP: Record<string, string> = {
  adventurer: "adventurer",
  adventurerNeutral: "adventurer-neutral",
  avataaars: "avataaars",
  avataaarsNeutral: "avataaars-neutral",
  bigEars: "big-ears",
  bigEarsNeutral: "big-ears-neutral",
  bigSmile: "big-smile",
  bottts: "bottts",
  botttsNeutral: "bottts-neutral",
  croodles: "croodles",
  croodlesNeutral: "croodles-neutral",
  funEmoji: "fun-emoji",
  icons: "icons",
  identicon: "identicon",
  lorelei: "lorelei",
  loreleiNeutral: "lorelei-neutral",
  micah: "micah",
  miniavs: "miniavs",
  notionists: "notionists",
  notionistsNeutral: "notionists-neutral",
  openPeeps: "open-peeps",
  personas: "personas",
  pixelArt: "pixel-art",
  pixelArtNeutral: "pixel-art-neutral",
  rings: "rings",
  shapes: "shapes",
  thumbs: "thumbs",
};

export const AVATAR_STYLES = {
  adventurer: {
    id: "adventurer",
    name: "Приключенец",
    style: adventurer,
    description: "Классический стиль приключений",
    urlKey: STYLE_URL_MAP.adventurer,
  },
  adventurerNeutral: {
    id: "adventurerNeutral",
    name: "Приключенец (нейтральный)",
    style: adventurerNeutral,
    description: "Нейтральная версия приключенца",
    urlKey: STYLE_URL_MAP.adventurerNeutral,
  },
  avataaars: {
    id: "avataaars",
    name: "Аватаары",
    style: avataaars,
    description: "Популярный стиль с множеством вариаций",
    urlKey: STYLE_URL_MAP.avataaars,
  },
  avataaarsNeutral: {
    id: "avataaarsNeutral",
    name: "Аватаары (нейтральный)",
    style: avataaarsNeutral,
    description: "Нейтральные аватаары",
    urlKey: STYLE_URL_MAP.avataaarsNeutral,
  },
  bigEars: {
    id: "bigEars",
    name: "Большие уши",
    style: bigEars,
    description: "Милые персонажи с большими ушами",
    urlKey: STYLE_URL_MAP.bigEars,
  },
  bigEarsNeutral: {
    id: "bigEarsNeutral",
    name: "Большие уши (нейтральный)",
    style: bigEarsNeutral,
    description: "Нейтральные персонажи с большими ушами",
    urlKey: STYLE_URL_MAP.bigEarsNeutral,
  },
  bigSmile: {
    id: "bigSmile",
    name: "Большая улыбка",
    style: bigSmile,
    description: "Весёлые персонажи с улыбками",
    urlKey: STYLE_URL_MAP.bigSmile,
  },
  bottts: {
    id: "bottts",
    name: "Роботы",
    style: bottts,
    description: "Роботизированные аватары",
    urlKey: STYLE_URL_MAP.bottts,
  },
  botttsNeutral: {
    id: "botttsNeutral",
    name: "Роботы (нейтральный)",
    style: botttsNeutral,
    description: "Нейтральные роботы",
    urlKey: STYLE_URL_MAP.botttsNeutral,
  },
  croodles: {
    id: "croodles",
    name: "Крудельс",
    style: croodles,
    description: "Забавные каракульные персонажи",
    urlKey: STYLE_URL_MAP.croodles,
  },
  croodlesNeutral: {
    id: "croodlesNeutral",
    name: "Крудельс (нейтральный)",
    style: croodlesNeutral,
    description: "Нейтральные каракульные персонажи",
    urlKey: STYLE_URL_MAP.croodlesNeutral,
  },
  funEmoji: {
    id: "funEmoji",
    name: "Весёлые эмодзи",
    style: funEmoji,
    description: "Разнообразные смайлики",
    urlKey: STYLE_URL_MAP.funEmoji,
  },
  icons: {
    id: "icons",
    name: "Иконки",
    style: icons,
    description: "Набор различных иконок",
    urlKey: STYLE_URL_MAP.icons,
  },
  identicon: {
    id: "identicon",
    name: "Идентикон",
    style: identicon,
    description: "Уникальные идентификаторы на основе seed",
    urlKey: STYLE_URL_MAP.identicon,
  },
  lorelei: {
    id: "lorelei",
    name: "Лорелей",
    style: lorelei,
    description: "Стилизованные человеческие аватары",
    urlKey: STYLE_URL_MAP.lorelei,
  },
  loreleiNeutral: {
    id: "loreleiNeutral",
    name: "Лорелей (нейтральный)",
    style: loreleiNeutral,
    description: "Нейтральные стилизованные аватары",
    urlKey: STYLE_URL_MAP.loreleiNeutral,
  },
  micah: {
    id: "micah",
    name: "Майка",
    style: micah,
    description: "Уникальные персонажи в стиле Майки",
    urlKey: STYLE_URL_MAP.micah,
  },
  miniavs: {
    id: "miniavs",
    name: "Мини-аватары",
    style: miniavs,
    description: "Маленькие детализированные аватары",
    urlKey: STYLE_URL_MAP.miniavs,
  },
  notionists: {
    id: "notionists",
    name: "Ноушионисты",
    style: notionists,
    description: "Стиль вдохновленный Notion",
    urlKey: STYLE_URL_MAP.notionists,
  },
  notionistsNeutral: {
    id: "notionistsNeutral",
    name: "Ноушионисты (нейтральный)",
    style: notionistsNeutral,
    description: "Нейтральная версия стиля Notion",
    urlKey: STYLE_URL_MAP.notionistsNeutral,
  },
  openPeeps: {
    id: "openPeeps",
    name: "Open Peeps",
    style: openPeeps,
    description: "Открытые персонажи из библиотеки Peeps",
    urlKey: STYLE_URL_MAP.openPeeps,
  },
  personas: {
    id: "personas",
    name: "Персонажи",
    style: personas,
    description: "Различные человеческие персонажи",
    urlKey: STYLE_URL_MAP.personas,
  },
  pixelArt: {
    id: "pixelArt",
    name: "Пиксель-арт",
    style: pixelArt,
    description: "Пиксельные аватары",
    urlKey: STYLE_URL_MAP.pixelArt,
  },
  pixelArtNeutral: {
    id: "pixelArtNeutral",
    name: "Пиксель-арт (нейтральный)",
    style: pixelArtNeutral,
    description: "Нейтральные пиксельные аватары",
    urlKey: STYLE_URL_MAP.pixelArtNeutral,
  },
  rings: {
    id: "rings",
    name: "Кольца",
    style: rings,
    description: "Геометрические аватары из колец",
    urlKey: STYLE_URL_MAP.rings,
  },
  shapes: {
    id: "shapes",
    name: "Фигуры",
    style: shapes,
    description: "Аватары из геометрических фигур",
    urlKey: STYLE_URL_MAP.shapes,
  },
  thumbs: {
    id: "thumbs",
    name: "Большие пальцы",
    style: thumbs,
    description: "Милые персонажи с большими пальцами",
    urlKey: STYLE_URL_MAP.thumbs,
  },
} as const;

export const AVATAR_STYLES_LIST = Object.values(AVATAR_STYLES);

export type AvatarStyleId = keyof typeof AVATAR_STYLES;
